Added community repos to the list
strongloop-internal/github-tools pull request #23
Opened 2017-01-11 21:19 UTC by cgole

2017-01-12 00:43 UTC, superkhau requested changes

2017-01-12 00:43 UTC, superkhau commented on projects/loopback.json
> +    "strongloop-community/loopback-connector-sqlite3",
i think we only need:
- loopback-connector-redis
- loopback-connector-sqlite3
for now. We can add manually for the other repos that need in the future.

2017-01-12 09:14 UTC, bajtos commented on projects/loopback.json
> +    "strongloop-community/loopback-connector-sqlite3",
+1

I would personally not bother with adding any strongloop-community repositories.

2017-01-13 00:51 UTC, superkhau commented on projects/loopback.json
> +    "strongloop-community/loopback-connector-sqlite3",
I think @cgole needs us to add the milestone markers for accountability/tracking velocity during sprints -- for example I needed to add Sprint 27 milestone for landing that redis fix (of course I prefer less process being agile n all, but it's easier than asking me later what I worked on when she can filter herself via ZH using the milestone label).

2020-05-15 09:52 UTC, closed without merging